apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - servicemonitor.yaml
configMapGenerator:
  - name: landing-zone-demo-dashboard
    files:
      - landing-zone-demo.json=grafana-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
