apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-zone-demo-app
  labels:
    app: landing-zone-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-zone-demo-app
  template:
    metadata:
      labels:
        app: landing-zone-demo-app
    spec:
      containers:
        - name: landing-zone-demo-app
          image: landing-zone-demo-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
