apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-zone-demo-app
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-zone-demo-app
                port:
                  number: 80
