apiVersion: v1
kind: Service
metadata:
  name: landing-zone-demo-app
  namespace: demo
  labels:
    app: landing-zone-demo-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aks"
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "REPLACE_WITH_AKS_BACKEND_IP"
spec:
  selector:
    app: landing-zone-demo-app
  ports:
    - name: http
      protocol: TCP
      port: 80 # Service port
      targetPort: 8080 # Pod port
  type: LoadBalancer
