apiVersion: v1
kind: ServiceAccount
metadata:
  name: landing-zone-demo
  namespace: demo
  labels:
    app.kubernetes.io/name: landing-zone-demo-app
    app.kubernetes.io/part-of: landing-zone-demo
  annotations:
    azure.workload.identity/client-id: REPLACE_WITH_MANAGED_IDENTITY_CLIENT_ID
